### ISSUE TITLE
How to display dynamic point clouds in my local folder?

### ISSUE THREAD

**Issue by sunmingliu** [cwi-dis/cwipc_unity_sample#1]
How to use cwipc to convert local point clouds into the format readable by cwipc_unity?

**Comment by jackjansen** [comment]
You shouldn't have to convert them, if the point clouds are compatible with cwipc and are all the same type and named sequentially. Just put the directory name into the `cwipc_playback` prefab.

You can preview with the command line utility `cwipc_view --playback directory`.

If your point clouds are not compatible (for example different size, or different origin) you can convert them with the swiss-army-knife tool `cwipc_grab`. 

Check out `https://github.com/cwi-dis/cwipc_test` and see the `Samples` directory for some sample sequences, and for some instructions on converting.

**Comment by sunmingliu** [comment]
Sorry, I cannot find the cwipc_playback prefab in Assets/Samples.  Currently, I can view loot sequence in `VRStreamingPointCLoudViewer ` scene in VR point cloud extensions folder.  Meanwhile, I can also view dynamic loot through CMD (cwipc_view --playback directory). However, I still cannot view dynamic loot in unity. Please help me!

**Comment by jackjansen** [comment]
Ah, I wasn't clear enough. The prefabs are in `Packages/CWI Point Cloud Support/Runtime/Prefabs`.
We've put things in `Assets/Samples` only if we think you will probably want to change them, or use them as the basis of your own work. If we think an asset is in principle complete we leave it in the package.

You could also look at the scene `VRPrerecordedPointcloudPlayback`, which does exactly what you want (after you've adapted the pathname in the `PointCloudPlayback` behaviour on the `cwipc_playback` game object).

**Comment by sunmingliu** [comment]
Sorry. I put the github project `[cwipc_test](https://github.com/cwi-dis/cwipc_test)` in right path and set corresponding directory name for `cwipc_playback ` prefab as the picture 1 shows. However, I encounter the `cwipc_read ` error as picture 2 shows.  I also test CMD( `cwipc_view --playback loot-xxxK-4tiles` ) and encountered the same issue as picture 3 shows.

Besides, from my understanding, the samples include loot-compressed (.cwipc), which represents encoded point clouds by the cwipc encoder, and loot-xxxK-4tiles (.cwipcdump), which represents the decoded point clouds. In the `VRPrerecordedPointcloudViewer` scene, the `cwipc_playback` object is responsible for reading and displaying the decoded point clouds from the loot-xxxK-4tiles. In the `VRstreamingPointcloudViewer` scene, `cwipc_playback_stream` object is responsible for encoded pointclouds  from `tcp://192.16.197.145:8089`. Why `cwipc_playback_stream` prefab is also set dirName  from `../Samples/loot-110k-4tiles`  and read decoded point clouds?
<img width="539" alt="cwipc_path" src="https://github.com/user-attachments/assets/5e356847-9b19-4d1c-bfea-1858dd228d03" />
<img width="490" alt="cwipc_read" src="https://github.com/user-attachments/assets/338625f4-4016-4b55-b534-ed6adacfe781" />
<img width="454" alt="CMD" src="https://github.com/user-attachments/assets/f5f4e2ce-6b7f-45a4-9f84-d827a6d591ea" />
<img width="539" alt="tcp" src="https://github.com/user-attachments/assets/6a428967-cdcd-4667-af2b-a01052ae941a" />

**Comment by jackjansen** [comment]
Ah! I think you haven't enabled `git lfs` when you checked out the `cwipc_test` repository! The point clouds are large binary blobs, so they have to be stored under lfs.

In the cwipc_test directory, do

```
git lfs install
git lfs fetch --all
git update
```

**Comment by jackjansen** [comment]
And on the other question:

> Why cwipc_playback_stream prefab is also set dirName from ../Samples/loot-110k-4tiles and read decoded point clouds?

This is laziness on our side: we implemented `StreamedPointCloudReader` after `PointCloudPlayback`, and we did a quick-and-dirty implementation with a subclass. Fine for us, because we know this, but not for you. Sorry!

**Comment by sunmingliu** [comment]
Thanks. I have obtained the complete loot-compressed files (.cwipc) and loot-xxxK-4tiles (.cwipcdump). When I try to convert `.ply` files in original loot dataset to `.cwipcdump` files as [cwipc_test ](https://github.com/cwi-dis/cwipc_test/blob/master/Samples/readme.md) instructed, I encountered an issue as picture shows. 
`CMD: cwipc_view --filter 'transform(-200,-300,0.0018)' --playback xx/xx/xx/loot/Ply` 
By the way, the transform originally had four parameters, but I removed the 0 as instructed.
<img width="487" alt="convert" src="https://github.com/user-attachments/assets/57b1faea-cc98-4334-aa3e-a3271ff2123d" />

**Comment by jackjansen** [comment]
You say: _" I removed the 0 as instructed"_ but that instruction is wrong, sorry! The `0` should stay there (as it is in the subsequent command lines).

**Comment by sunmingliu** [comment]
Thanks so much. I have changed the parameters, but it still shows AttributeError that 'str' obiect has no attribute 'CustomFilter'. Is there something installed wrong? Please help me check it. By the way, I'm curious what does '4tiles' mean in 'cwipc_test/Samples/loot-xxx-4tiles'.

**Comment by jackjansen** [comment]
On the "4tiles" meaning: the point clouds have been tiled into 4 tiles. The data that we actually store per point is `X, Y, Z, R, G, B, Tilenum`. Normally you don't have to worry about this and you can ignore it. But for some use cases (such as compressing and transmitting over the net) you can use `cwipc_tilefilter()` to split the point cloud stream into its 4 tiles, and get a 4-fold speedup by parallelising the encoder.

On the AttributeError: that sounds like a bug that was fixed quite some time ago (in the underlying cwipc). Can you tell me which version cwipc you have installed? (`cwipc_view --version` output).

Could you try uninstalling cwipc and re-installing the latest nightly build (SHA 79071540a2273ee8610baeb73c2f4be88e4fac2f).

**Comment by sunmingliu** [comment]
Thank you for your assistance. I understand now. The version I previously installed was v7.5.3, and I am currently trying to re-install the latest nightly build.
